version: "3"
services:
  airflow:
    image: apache/airflow:slim-latest-python3.9
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@biyu.com &&
      airflow webserver &
      airflow scheduler"
    ports:
      - "8080:8080"
    volumes:
      - ./download_launches.py:/opt/airflow/dags/download_rocket_launches.py
    container_name: airflow
